### ISSUE TITLE
Setup.sh give errors

### ISSUE THREAD

**Issue by SP-NL** [ajinabraham/CMSScan#12]
aftr running setup.sh i get these errors
/usr/bin/python3: No module named pip
./setup.sh: 9: ./setup.sh: virtualenv: not found
./setup.sh: 10: .: Can't open venv/bin/activate

Also I can find any info to  make this run as daemon so it runs all the time (also when i restart)
if i type http://IP_of _mymachine No page?

**Comment by ajinabraham** [comment]
You need to install correct version of ruby as required by wpscan
