### ISSUE TITLE
errors  no report

### ISSUE THREAD

**Issue by SP-NL** [ajinabraham/CMSScan#13]
We got the Webgui running and we can scan with WPSscan by CLI but when we use WPSscan
When we us the GUI this error is shown

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/CMSScan/core.py", line 54, in scan
    self.scan_wp()
  File "/home/CMSScan/core.py", line 32, in scan_wp
    self.write_to_db(result)
  File "/home/CMSScan/core.py", line 23, in write_to_db
    dbo = get_db()
  File "/home/CMSScan/db.py", line 10, in get_db
    dbo = g._database = sqlite3.connect(DATABASE)
sqlite3.OperationalError: unable to open database file

**Comment by SP-NL** [comment]
I tried it on a other host and it looks the DB is not a problem here: I can start a scan but get this error:
"scan_aborted": "Permission denied @ rb_sysopen - /tmp/wpscan/cache/bec2fccec4afe99022a88eb2d4b4ade5/253745390",
    "trace": ⊖[
        "/var/lib/gems/2.5.0/gems/cms_scanner-0.0.41.1/lib/cms_scanner/cache/file_store.rb:45:in `write'",
       ⊖        "/var/lib/gems/2.5.0/gems/cms_scanner-0.0.41.1/lib/cms_scanner/cache/file_store.rb:45:in `write_entry'",
        "/var/lib/gems/2.5.0/gems/cms_scanner-0.0.41.1/lib/cms_scanner/cache/typhoeus.rb:17:in `set'",
        "/var/lib/gems/2.5.0/gems/typhoeus-1.3.1/lib/typhoeus/request/cacheable.rb:5:in `response='",
        "/var/lib/gems/2.5.0/gems/typhoeus-1.3.1/lib/typhoeus/request/operations.rb:32:in `finish'",
        "/var/lib/gems/2.5.0/gems/typhoeus-1.3.1/lib/typhoeus/easy_factory.rb:164:in `block in set_callback'",
        "/var/lib/gems/2.5.0/gems/ethon-0.11.0/lib/ethon/easy/response_callbacks.rb:68:in `block in complete'",
        "/var/lib/gems/2.5.0/gems/ethon-0.11.0/lib/ethon/easy/response_callbacks.rb:68:in `each'",
        "/var/lib/gems/2.5.0/gems/ethon-0.11.0/lib/ethon/easy/response_callbacks.rb:68:in `complete'",
        "/var/lib/gems/2.5.0/gems/ethon-0.11.0/lib/ethon/easy/operations.rb:33:in `perform'",
        "/var/lib/gems/2.5.0/gems/typhoeus-1.3.1/lib/typhoeus/request/operations.rb:16:in `run'",
        "/var/lib/gems/2.5.0/gems/typhoeus-1.3.1/lib/typhoeus/request/cacheable.rb:18:in `run'",
        "/var/lib/gems/2.5.0/gems/typhoeus-1.3.1/lib/typhoeus/request/block_connection.rb:31:in `run'",
        "/var/lib/gems/2.5.0/gems/typhoeus-1.3.1/lib/typhoeus/request/stubbable.rb:25:in `run'",
        "/var/lib/gems/2.5.0/gems/typhoeus-1.3.1/lib/typhoeus/request/before.rb:26:in `run'",
        "/var/lib/gems/2.5.0/gems/cms_scanner-0.0.41.1/lib/cms_scanner/browser/actions.rb:44:in `process'",
        "/var/lib/gems/2.5.0/gems/cms_scanner-0.0.41.1/lib/cms_scanner/browser/actions.rb:10:in `get'",
       ⊖        "/var/lib/gems/2.5.0/gems/cms_scanner-0.0.41.1/app/controllers/core.rb:36:in `check_target_availability'",
        "/var/lib/gems/2.5.0/gems/wpscan-3.4.2/app/controllers/core.rb:57:in `before_scan'",
        "/var/lib/gems/2.5.0/gems/cms_scanner-0.0.41.1/lib/cms_scanner/controllers.rb:42:in `each'",
        "/var/lib/gems/2.5.0/gems/cms_scanner-0.0.41.1/lib/cms_scanner/controllers.rb:42:in `run'",
        "/var/lib/gems/2.5.0/gems/cms_scanner-0.0.41.1/lib/cms_scanner.rb:137:in `run'",
        "/var/lib/gems/2.5.0/gems/wpscan-3.4.2/bin/wpscan:15:in `block in <top (required)>'",
        "/var/lib/gems/2.5.0/gems/cms_scanner-0.0.41.1/lib/cms_scanner.rb:128:in `initialize'",
        "/var/lib/gems/2.5.0/gems/wpscan-3.4.2/bin/wpscan:5:in `new'",
        "/var/lib/gems/2.5.0/gems/wpscan-3.4.2/bin/wpscan:5:in `<top (required)>'",
        "/usr/local/bin/wpscan:23:in `load'",
        "/usr/local/bin/wpscan:23:in `<main>'"

**Comment by SP-NL** [comment]
I want to have this gui on a linux VM and add more stuff to it please mail me

**Comment by ajinabraham** [comment]
You have permissions issues it seems. If you need a virtualized environment. Why not use the dockerized version of CMSScan
