### ISSUE TITLE
Joomlascan can not scan https websites

### ISSUE THREAD

**Issue by SP-NL** [ajinabraham/CMSScan#14]
Also the joomlascan part does not work
After installing:
Installing LWP from the CPAN Shell
perl -MCPAN -eshell
cpan> install Bundle::LWP

install HTML::Tree
install HTML::Format
install LWP::Protocol::https
sudo cpan install LWP::Protocol::https
the Joomplascan works on http://Joomla site when i scan https website is see the error 
  (_  _)(  _  )(  _  )(  \/  )/ __) / __)  /__\  ( \( )
_)(   )(_)(  )(_)(  )    ( \__ \( (__  /(__)\  )  (
  \____) (_____)(_____)(_/\/\_)(___/ \___)(__)(__)(_)\_)
                        (1337.today)

    --=[OWASP JoomScan
    +---++---==[Version : 0.0.7
    +---++---==[Update Date : [2018/09/23]
    +---++---==[Authors : Mohammad Reza Espargham , Ali Razmjoo
    --=[Code name : Self Challenge
    @OWASP_JoomScan , @rezesp , @Ali_Razmjo0 , @OWASP

[+] Target uses HTTPS, but module LWP::Protocol::https is not available!

**Comment by ajinabraham** [comment]
You might have missing perl dependencies. Install `perl-LWP-Protocol-https`
