### ISSUE TITLE
WPScan - Incorrect --wp-content-dir option set

### ISSUE THREAD

**Issue by erwanlr** [ajinabraham/CMSScan#17]
The ```--wp-content-dir```, as set  at https://github.com/ajinabraham/CMSScan/blob/master/plugins/scanners.py#L56 is incorrect, there is no need to put the url in it. ```--wp-content-dir wp-content``` is enough.

However, I would recommend to leave this one out (unless the user sets one) as there are automatic detection for it in WPscan

**Comment by ajinabraham** [comment]
Thanks for pointing out.
