### ISSUE TITLE
where to insert the API for WPVulnDB? and other configurations for joomla and drupal

### ISSUE THREAD

**Issue by rajeshk28** [ajinabraham/CMSScan#23]

**Comment by ajinabraham** [comment]
Currently not supported. You need to modify the code to do so.

**Comment by angelperezleon** [comment]
Its been over a year now.. when are we lightly to see this supported.
As I am always hitting the limits:

```
"vuln_api": ⊖{
        "error": ⊖"No WPScan API Token given, as a result vulnerability data has not been output.\nYou can get a free API token with 25 daily requests by registering at https://wpscan.com/register"
```

and have edited the app inside the docker container by either doing:

    nano ~/.wpscan/scan.yml
or
    nano /usr/local/bin/scan.yml

or find / -name "wpscan"

```
cli_options:
  api_token: GFzzLFCsOjvaQ4lGh6TKdA(IMCOMPLETE)
```

Obviously have done the registration + API stuff over at https://wpscan.com/register
