### ISSUE TITLE
RECENT SCANS Not Show Target.

### ISSUE THREAD

**Issue by vncloudsco** [ajinabraham/CMSScan#25]
i using Prebuilt Image Docker on docker hub, it didn't work. I hit start scan but no target show.

![image](https://user-images.githubusercontent.com/41409442/90152230-cd356580-ddb1-11ea-8522-c96a85e8e0df.png)

Not target

![image](https://user-images.githubusercontent.com/41409442/90152129-ad9e3d00-ddb1-11ea-9819-ed22e0eaf87b.png)

**Comment by ajinabraham** [comment]
Recent scans will show it only if the scan has completed sucessfully.

**Comment by vncloudsco** [comment]
@ajinabraham thank you so much i saw it show up. however I hope to get status information after submitting the target.

**Comment by DJE98** [comment]
@ajinabraham @vncloudsco Nice info. Is there still a problem? Otherwise you can close the issue.

**Comment by vncloudsco** [comment]
@DJE98  yes. i close the issue.
