### ISSUE TITLE
[Feature Request] Manual CMS selection

### ISSUE THREAD

**Issue by IQNeoXen** [ajinabraham/CMSScan#3]
Hi there,

first of all - really great tool! Love it!
It would be nice if we could select the targeted CMS manually in case CMSScan doesn't recognize it.

Have a nice day,
Neo

**Comment by ajinabraham** [comment]
As of now, UI is designed with minimalized configuration in mind. However you can specify the CMS if you send a POST with url and cms name. Use the scheduler script. https://github.com/ajinabraham/CMSScan/blob/master/scheduler.py#L62-L64
