### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by angelperezleon** [ajinabraham/CMSScan#8]
Not an issue but a request to this great CMS vulnerability checker Ajin.

Is it possible to have like an admin function, so for example on the "Recent scans" section only admin logged in user can remove recent scans from the list?

**Comment by ajinabraham** [comment]
Added basic auth, available in latest master: https://github.com/ajinabraham/CMSScan#basic-auth

**Comment by ajinabraham** [comment]
If you need to protect only specific routes.
Set `app.config['BASIC_AUTH_FORCE'] = False` and use the decorator `@basic_auth.required`.
Ref: https://flask-basicauth.readthedocs.io/en/latest/
